# Generated by Django 5.2.14 on 2026-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_notify_comments_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='code_hash',
            field=models.CharField(max_length=128),
        ),
    ]
